export const translator = {
  first_name: 'Nombre',
  last_name: 'Apellido',
  age: 'Edad',
  birthdate: 'Nacimiento',
  type: 'Tipo',
  language: 'Lenguaje',
  role: 'Rol',
  company_id: 'Compañía',
  companyId: 'Compañía',
  search: 'Buscar',
  edit: 'Editar',
  create: 'Crear',
  detail: 'Detalle',
  createdAt: 'Creado',
  updatedAt: 'Actualizado',
  programmer: 'programador',
  designer: 'diseñador',
  languageId: 'programmer',
  typeId: 'designer',
}
